# -------------------------------------------------------
# Diseño de Lenguajes de Programación
# Parser file generated by the compiler.
# Francisco Rosal - 18676
# -------------------------------------------------------

class Parser():
	def __init__(self, tokens):
		self.tokens = tokens
		self.current_token_index = 0
		self.current_token = self.tokens[self.current_token_index]
		self.EstadoInicial()

	def update_current_token(self):
		if self.current_token_index < len(self.tokens) - 1:
			self.current_token_index += 1
			self.current_token = self.tokens[self.current_token_index]

	def EstadoInicial(self):
		while self.current_token['type'] in ['numero', 'menos', '(']:
			self.Instruccion()

			if self.current_token["value"] == ";":
				self.update_current_token()

	def Instruccion(self):
		resultado = 0
		resultado = self.Expresion(resultado)
		print(resultado)

	def Expresion(self, resultado):
		resultado1, resultado2 = 0, 0
		resultado1 = self.Termino(resultado1)
		while self.current_token['value'] in ['+', '-']:

			if self.current_token["value"] == "+":
				self.update_current_token()
				resultado2 = self.Termino(resultado2)
				resultado1 += resultado2

			if self.current_token["value"] == "-":
				self.update_current_token()
				resultado2 = self.Termino(resultado2)
				resultado1 -= resultado2

		return resultado1

	def Termino(self, resultado):
		resultado1, resultado2 = 0, 0
		resultado1 = self.Factor(resultado1)
		while self.current_token['value'] in ['*', '/']:

			if self.current_token["value"] == "*":
				self.update_current_token()
				resultado2 = self.Factor(resultado2)
				resultado1 *= resultado2

			if self.current_token["value"] == "/":
				self.update_current_token()
				resultado2 = self.Factor(resultado2)
				resultado1 /= resultado2

		return resultado1

	def Factor(self, resultado):
		signo = 1

		if self.current_token["value"] == "-":
			self.update_current_token()
			signo = -1

		resultado = self.Number(resultado)

		if self.current_token["value"] == "(":
			self.update_current_token()
			resultado = self.Expresion(resultado)
			self.update_current_token()

		return resultado * signo

	def Number(self, resultado):
		numero = None
		if self.current_token["type"] == "numero":
			numero = float(self.current_token["value"])
			self.update_current_token()
		return numero

Parser([{'type': 'menos', 'value': '-'}, {'type': 'numero', 'value': '5'}, {'type': 'mas', 'value': '+'}, {'type': 'numero', 'value': '4'}, {'type': 'por', 'value': '*'}, {'type': '(', 'value': '('}, {'type': 'numero', 'value': '10'}, {'type': 'div', 'value': '/'}, {'type': 'numero', 'value': '2'}, {'type': ')', 'value': ')'}, {'type': 'mas', 'value': '+'}, {'type': 'numero', 'value': '2'}, {'type': 'final', 'value': ';'}])
